mysql:
  enable: false
  user: root
  password: sicherespasswort
  database: Bansystem
  host: localhost
  port: 3306

# if IPautoban is disabled, every player with the bansys.notify permission gets a notification
IPautoban:
  enable: false
  banid: 9
  onlyNetworkBans: false

# apikey: if more than 100 players join a day then you have to enter your apikey.
#         To get the apikey simply go to https://vpnapi.io/ and create an account.
#         Now the apikey is on the dashboard.
VPN:
  enable: true
  autoban:
    enable: false
    ID: 11
  serverIP: 00.00.00.00
  apikey: ''

mute:
  blockedCommands:
    - /msg
    - /tell
    - /me
    - /whisper
    - /say

needReason:
  Unban: false
  Unmute: false

blacklist:
  words:
    enable: true
    autoban:
      enable: true
      id: 6
  ads:
    enable: true
    autoban:
      enable: true
      id: 7

# If you have the permission bansys.bypasschatdelay you are not affected.
chatdelay:
  enable: true
  delay: 3

# to add an ID simple use the command "/bansys ids create" or just copy an ID and change the attributes.
# Possible Types are: NETWORK, CHAT (please note that it is case-sensitive)
# The duration is calculated in seconds that means 1 day is 86400 duration.
# If onlyAdmins is enabled you need to have the permission bansys.ban.admin
IDs:
  '1':
    reason: Unerlaubte Clientmodification/Hackclient
    onlyAdmins: false
    lvl:
      '1':
        type: NETWORK
        duration: 2592000
      '2':
        type: NETWORK
        duration: -1
  '2':
    reason: Reportmissbrauch
    onlyAdmins: false
    lvl:
      '1':
        type: NETWORK
        duration: 864000
      '2':
        type: NETWORK
        duration: -1
  '3':
    reason: Unangebrachter Skin/Name
    onlyAdmins: false
    lvl:
      '1':
        type: NETWORK
        duration: 2592000
      '2':
        type: NETWORK
        duration: -1
  '4':
    reason: Crossteaming
    onlyAdmins: false
    lvl:
      '1':
        type: NETWORK
        duration: 864000
      '2':
        type: NETWORK
        duration: -1
  '5':
    reason: Bugusing
    onlyAdmins: false
    lvl:
      '1':
        type: NETWORK
        duration: 864000
      '2':
        type: NETWORK
        duration: -1
  '6':
    reason: Chat Verhalten
    onlyAdmins: false
    lvl:
      '1':
        type: CHAT
        duration: 86400
      '2':
        type: CHAT
        duration: 604800
      '3':
        type: CHAT
        duration: 1209600
      '4':
        type: CHAT
        duration: 2592000
      '5':
        type: CHAT
        duration: -1
  '7':
    reason: Werbung
    onlyAdmins: false
    lvl:
      '1':
        type: CHAT
        duration: 604800
      '2':
        type: CHAT
        duration: 1209600
      '3':
        type: CHAT
        duration: 2592000
      '4':
        type: CHAT
        duration: -1
  '8':
    reason: Alt-Account
    onlyAdmins: false
    lvl:
      '1':
        type: NETWORK
        duration: -1
  '9':
    reason: Bannumgehung
    onlyAdmins: false
    lvl:
      '1':
        type: NETWORK
        duration: -1
  '10':
    reason: Sicherheitsbann
    onlyAdmins: false
    lvl:
      '1':
        type: NETWORK
        duration: -1
  '11':
    reason: VPN
    onlyAdmins: false
    lvl:
      '1':
        type: NETWORK
        duration: -1
  '99':
    reason: ยง4EXTREM
    onlyAdmins: true
    lvl:
      '1':
        type: NETWORK
        duration: -1
