name: BanSystem
version: 2.9
author: Tobi
main: net.coalcube.bansystem.spigot.BanSystemSpigot
commands:
  ban:
  unban:
  unmute:
  bansystem:
  bansys:
  kick:
  history:
  check:
  deletehistory:
  delhistory: